version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ovladni_mechyr_development
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ovladni_mechyr_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./ovladni_mechyr_be
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: 3.2.2
        RAILS_ENV: development
        BUNDLE_WITHOUT: ""
    image: ovladni_mechyr_be:dev
    # Using bash to remove pid file just in case
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - ./ovladni_mechyr_be:/rails
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: ovladni_mechyr_development
      DATABASE_PASSWORD: password
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
